#!/bin/bash                                                                                                                                                                                                                                                              

#BSUB -q prod.med
#BSUB -n 1
#BSUB -R "rusage [ngpus_excl_p=1]"

module load Anaconda3
source /u/pus/venv/bin/activate

#BSUB -J "logs_dcis"
#BSUB -o "logs_dcis"
#BSUB -e "logs_dcis.stderr"

python3 -u inference.py -1

