#!/bin/bash                                                                                                                                                                                                                                                              

#BSUB -q prod.med
#BSUB -n 1
#BSUB -R "rusage [ngpus_excl_p=1]"

module load Anaconda3
source /u/pus/venv/bin/activate

#BSUB -J "proc_udh"
#BSUB -o "proc_udh"
#BSUB -e "proc_udh.stderr"

python3 -u inference.py -1 -1

