dist: xenial
env:
  global:
  # do not load /etc/boto.cfg with Python 3 incompatible plugin
  # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
  - BOTO_CONFIG=/doesnotexist
services:
- docker
language: python
python:
- 3.6
before_install:
- sudo apt update
- sudo apt-get install libopenjpeg5 libtiff-tools libopenjpeg-dev #openslide-tools
- wget https://github.com/openslide/openslide/releases/download/v3.4.1/openslide-3.4.1.tar.gz
- tar xvf openslide-3.4.1.tar.gz
- cd openslide-3.4.1
- ./configure && make && sudo make install
- cd ..
- sudo apt-get install libopencv-dev python-opencv
- sudo apt-get install python3-openslide
install:
- pip3 install -U pip
- pip3 install --progress-bar off -r requirements.txt
- pip3 install .
script:
- python3 -c "import histocartography"
- python3 -c "import cv2 as cv"
- python3 -m unittest discover  -v
# And now, make travis train
- export MLFLOW_TRACKING_URI=http://experiments.traduce.zc2.ibm.com:5000                
- export MLFLOW_S3_ENDPOINT_URL=http://data.digital-pathology.zc2.ibm.com:9000
- mlflow run bin/fra_gleason2019
#- docker build -t histocartography:test .
#- docker run -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" -t histocartography:test python3 -m unittest discover  -v
notifications:
  slack: ibm-research:IQCmAJFXrlp1SfvqWsNfYpTg