dist: trusty

services:
  - docker

language: python

python:
  - 3.5
  - 3.6

before_script:
  # install the package
  - pip3 install .

script:
  # test import
  - python3 -c "import blueprint"

  # ensure installed commands helps run successfully
  # (add as required)
  - salutation -h

  # run unit tests
  - python3 -m unittest discover -s test -p "test_*" -v

  # check docker build and test inside
  - docker build -t blueprint:test .
  - docker run -t blueprint:test python3 -m unittest discover -s test -p "test_*" -v
