dist: xenial
services:
- docker
language: python
python:
- 3.6
before_install:
- sudo apt update
- sudo apt-get install openslide-tools
- sudo apt-get install libopencv-dev python-opencv
- sudo apt-get install python3-openslide
install:
- pip3 install -U pip
- pip3 install --progress-bar off -r requirements.txt
- pip3 install .
script:
#- python3 -c "import histocartography"
#- python3 -c "import cv2 as cv"
#- training_script -h
#- python3 -m unittest discover  -v
- docker build -t histocartography:test .
- docker run -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" -t histocartography:test python3 -m unittest discover  -v
notifications:
  slack: ibm-research:IQCmAJFXrlp1SfvqWsNfYpTg
