dist: trusty

services:
  - docker

language: python

python:
  - 3.5
  - 3.6

before_script:
  # install the package
  - pip3 install .

script:
  # test import
  - python3 -c "import histocartography"

  # ensure installed commands helps run successfully
  # (add as required)
  - training_script -h

  # run unit tests
  - python3 -m unittest discover -s test -p "test_*" -v

  # check docker build and test inside
  - docker build -t histocartography:test .
  - docker run -t histocartography:test python3 -m unittest discover -s test -p "test_*" -v

notifications:
  slack: ibm-research:IQCmAJFXrlp1SfvqWsNfYpTg
