vm:
  size: 2x-large
language: python
python:
  - 3.7
before_install:
  # download and install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # create and activate the build/test environment
  - conda create -q -n histocartography python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate histocartography
  - python --version
  - pip install -U pip==20.2.4
  - pip install sphinx autodoc sphinx_autodoc_typehints sphinx_rtd_theme myst_parser better_apidoc
install:
  - conda env update -q --file environment.yml
  - pip install black pep8 
  - pip install codecov
  - pip install -e .
script:
  # tests
  - coverage run -m unittest discover -s test -p "test_*" -v
  # build the docs
  #  cd docs && make html && cd ..
  - cd docs && make html && cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    local_dir: docs/_build/html
    github_url: $GITHUB_URL
    on:
      branch: main
