language: python
python:
  - 3.7
before_install:
  # download and install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # create and activate the build/test environment
  - conda create -q -n histocartography python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate histocartography
  - pip install -U pip==20.2.4
install:
  # install rdkit
  - conda env update --file environment.yml
  - pip install https://files.pythonhosted.org/packages/b2/f9/e6d6b55583078f62ead8b3785109832e1d0b4ae6cddbf1bfe9a5f767de6a/dgl-0.4.3.post2-cp37-cp37m-manylinux1_x86_64.whl
  # install development dependencies
  #- pip install -r dev_requirements.txt
  # install dependencies
  #- pip install -r requirements.txt
  # install the module
  - pip install -e .
script:
  # style checking
  - python -m black histocartography --check --diff --color
  - python -m pep8 --ignore=E501 histocartography
  # static type checking
  # - python -m mypy histocartography
  # tests
  - python -m unittest discover -s test -p "test_*" -v
  # build the docs
  #  cd docs && make html && cd ..
notifications:
  slack: ibm-research:Ffs4Jurpvx5oThkOEsdG4zB5