dist: trusty
services:
- docker
language: python
python:
- 3.5
install:
- pip3 install -U pip
- pip3 install --progress-bar off -r requirements.txt
- pip install pys3
- pip3 install .
script:
- python3 -c "import histocartography"
- training_script -h
- python3 -m unittest discover  -v
- docker build -t histocartography:test .
- docker run -t histocartography:test python3 -m unittest discover  -v
notifications:
  slack: ibm-research:IQCmAJFXrlp1SfvqWsNfYpTg
