name: histocartography
dependencies:
  - python>=3.6
  - pip
  - pip:
    - torch>=1.4.0
    - dgl>=0.5.1
    - tqdm>=4.35.0
    - mlflow>=1.6.0
    - pandas>=0.24.2
    - matplotlib>=3.1.1
    - h5py>=2.9.0
    - sklearn
    - seaborn>=0.9.0
    - torchvision