name: histocartography
dependencies:
    - python==3.9
    - pip
    - pip:
        - dgl
        - torch
        - torchvision
        - h5py
        - matplotlib
        - networkx
        - opencv-python
        - pandas
        - Pillow
        - PyYAML
        - scikit-image
        - scikit-learn
        - scipy
        - seaborn
        - tqdm