name: test
dependencies:
    - python==3.9
    - pip
    - pip:
        - dgl
        - torch
        - torchvision
        - h5py
        - matplotlib
        - networkx
        - opencv-python
        - pandas
        - Pillow
        - PyYAML
        - scikit_image
        - scikit_learn
        - scipy
        - seaborn
        - tqdm