#!/bin/bash                                                                                                                                                                                                                                                              

#BSUB -q prod.med
#BSUB -n 1
#BSUB -R "rusage [ngpus_excl_p=1]"

conda activate hovernet

#BSUB -J "log_benign"
#BSUB -o "log_benign"
#BSUB -e "log_benign.stderr"

python3 -u main.py --data_param=dataT --tumor_type=benign